### ISSUE TITLE
Implementing the GBGCN in google colab

### ISSUE THREAD

**Issue by Ali-khn** [Sweetnow/group-buying-recommendation#2]
Hi,
After installing setup.py file from the mentioned frame work in the GitHub, I tried to run the GBGCN.py file by this command in Google Colab, "! python  GBGCN.py  train --tag 'true' --SL2 0.001 --L2 0.001 --lr 1e-2  --layer 2 --alpha 0.6 --beta 0.01
". The below Errors showed: ( Any help to solve these errors and run the file properly would be appreciated! Just to mentioned that when I tried to run the whole data on GBGCN.py, it was not successful. I think the not enough RAM on colab was the problem( my colab RAM is around 12 GB) so I tried to reduce the size of BeiBei data set( 0.01 of the data set) to tackle this issue. Then these errors showed)
--------------------------------------------------------------------------------------------------------------------------------------------
INFO:root:Environment Arguments(OrderedDict([('dataset', 'BeiBei'), ('device', [0]), ('sample_epoch', 500), ('sample_worker', 16), ('epoch', 500), ('tag', 'true')]))
INFO:root:Dataloader Arguments(OrderedDict([('batch_size', 4096), ('batch_worker', 2), ('test_batch_size', 128), ('test_batch_worker', 2)]))
INFO:root:Hyperparameter Arguments(OrderedDict([('embedding_size', 32), ('act', 'sigmoid'), ('pretrain', True), ('SL2', [0.001]), ('L2', [0.001]), ('lr', [0.01]), ('layer', [2]), ('alpha', [0.6]), ('beta', [0.01])]))
INFO:root:{'comment': '固定参数', 'user': 'user', 'visdom': {'server': '127.0.0.1', 'port': {'BeiBei_itemrec': 16670, 'BeiBei_grouprec': 16670, 'BeiBei_SIGR': 16670, 'BeiBei': 16670, 'comment': '16671 is temporary'}}, 'training': {'test_interval': 5, 'early_stop': 50, 'overfit': {'protected_epoch': 10, 'threshold': 1}}, 'dataset': {'path': './BeiBei', 'seed': 123, 'use_backup': True}, 'logger': {'path': './log', 'policy': 'best'}, 'metric': {'target': {'type': 'NDCG', 'topk': 10}, 'metrics': [{'type': 'Recall', 'topk': 3}, {'type': 'Recall', 'topk': 5}, {'type': 'Recall', 'topk': 10}, {'type': 'Recall', 'topk': 20}, {'type': 'NDCG', 'topk': 3}, {'type': 'NDCG', 'topk': 5}, {'type': 'NDCG', 'topk': 10}, {'type': 'NDCG', 'topk': 20}]}}
INFO:root:{'BeiBei': {'GBMF': ''}}
DEBUG:root:Load BeiBei/BeiBei/BeiBei-neg-500-123-default.pkl
DEBUG:root:finish loading neg sample
INFO:root:GPU search space: [0]
INFO:root:Auto select GPU 0
WARNING:visdom:Setting up a new session...
Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.7/dist-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/local/lib/python3.7/dist-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.7/http/client.py", line 1277, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1323, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1272, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1032, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 972, in send
    self.connect()
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fd8435d5c50>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.7/dist-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=16670): Max retries exceeded with url: /env/GBGCN_true-32-0.01-0.001-0.001-2-0.6-0.01-sigmoid-True-True (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd8435d5c50>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/visdom/__init__.py", line 711, in _send
    data=json.dumps(msg),
  File "/usr/local/lib/python3.7/dist-packages/visdom/__init__.py", line 677, in _handle_post
    r = self.session.post(url, data=data)
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=16670): Max retries exceeded with url: /env/GBGCN_true-32-0.01-0.001-0.001-2-0.6-0.01-sigmoid-True-True (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd8435d5c50>: Failed to establish a new connection: [Errno 111] Connection refused'))
INFO:visdom:Socket refused connection, running socketless
ERROR:visdom:[Errno 111] Connection refused
ERROR:websocket:error from callback <function Visdom.setup_socket.<locals>.on_close at 0x7fd84346ec20>: on_close() takes 1 positional argument but 3 were given
  File "/usr/local/lib/python3.7/dist-packages/websocket/_app.py", line 407, in _callback
    callback(self, *args)
Traceback (most recent call last):
  File "GBGCN.py", line 556, in <module>
    torch.optim.SGD)
  File "/usr/local/lib/python3.7/dist-packages/librecframework-1.3.0-py3.7.egg/librecframework/pipeline.py", line 633, in during_running
    model_class, other_args, trainhooks, optim_type)
  File "/usr/local/lib/python3.7/dist-packages/librecframework-1.3.0-py3.7.egg/librecframework/pipeline.py", line 239, in during_running
    model.load_pretrain(self._pretrain[self._eam['dataset']])
  File "GBGCN.py", line 102, in load_pretrain
    pretrain = torch.load(path, map_location='cpu')
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 381, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: ''

**Comment by Sweetnow** [comment]
## Visdom-related Exception

The reason of such exception is that there is not visdom server working on the given ip and port in `config/config.json`.

We have updated librecframework to 1.3.2 to support disabling visdom.
*PS: We have added `install.sh` to help install librecframework from sources.*

The method to disable visdom is setting `visdom->server` to empty string in `config/config.json`.

If you want to use visdom to visualize training processes, you can install visdom by pip and then start it following [Docs](https://github.com/fossasia/visdom#command-line-options):

```bash
pip install visdom==0.1.8.9 [--user]
python -m visdom.server -port XXXX 
```

*PS: The port should be matched `visdom->port->BeiBei` in `config/config.json`*

## FileNotFoundError

The reason of such exception is that the `pretrain` flag is set to True by default for GBGCN while `BeiBei->GBMF` in `config/pretrain.json` is empty string.

You can add `--no-pretrain` flag to disable it when starting the code.

**The better solution is:**
1. Train GBMF firstly.
2. Set `BeiBei->GBMF` in `config/pretrain.json` to the path of the best GBMF model as pretrain model.
3. Train GBGCN.

**Comment by Sweetnow** [comment]
For memory issue, you can try to sample some users and items from the raw dataset.
The main memory consumption comes from the user-item graph (190080×30782).

**Comment by Sweetnow** [comment]
Beside exceptions above, the new implementation (v0.6) of DGL changes some features, which will raise
```python
DGLError(Cannot assign node feature "h" on device cuda:0 to a graph on device cpu. Call DGLGraph.to() to copy the graph to the same device).
```

We will fix it soon.

**Comment by Sweetnow** [comment]
> Beside exceptions above, the new implementation (v0.6) of DGL changes some features, which will raise
> 
> ```python
> DGLError(Cannot assign node feature "h" on device cuda:0 to a graph on device cpu. Call DGLGraph.to() to copy the graph to the same device).
> ```
> 
> We will fix it soon.

You can try the new codes (both librecframework and this repo)

**Comment by Ali-khn** [comment]
Thanks for your time and consideration.
